version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: reservas_db_container
    environment:
      POSTGRES_USER: admin_reservas
      POSTGRES_PASSWORD: root
      POSTGRES_DB: reservas_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_reservas_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_reservas_data:
