# Configuración de la Base de Datos (PostgreSQL en Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/reservas_db
spring.datasource.username=admin_reservas
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' leerá tus clases Java y creará/modificará las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update

# Auditoría de SQL en Consola (Esencial para ver qué hace Hibernate por detrás)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ajuste de la zona horaria para el manejo correcto de fechas locales
spring.jackson.time-zone=America/Lima
